### ISSUE TITLE
Ability to skip tracing for certain URL patterns

### ISSUE THREAD

**Issue by pavolloffay** [opentracing-contrib/java-web-servlet-filter#15]
This should be helpful for use cases like: checking application health on openshift, disable favicon, swagger docs..

**Comment by pavolloffay** [comment]
I am thinking about implementation, I'm wondering whether setting `sampling.priority=0` on newly started server span would be the cleanest solution here.

cc @bhs @yurishkuro @adriancole

**Comment by bhs** [comment]
@pavolloffay IMO it would make more sense to just omit the `Span` entirely... of course this is a judgement call, but if the goal is to ignore something it would be better in my mind to skip the cost of allocating Spans just to discard them shortly thereafter.

**Comment by codefromthecrypt** [comment]
I agree with @bhs: instrumentation policy is different than sampling policy. Simpler to not instrument always uninteresting paths (by affecting which paths the trace filter applies to). If that's not possible or practical, then move to sampling policy

**Comment by pavolloffay** [comment]
Thanks, I was curious what opinion do you have on this. 

I asked because this will require to pass something in servlet attributes to let know higher layers (spring MVC, jaxrs) know that request is not traced. Which is not so clean but would perform better.

**Comment by codefromthecrypt** [comment]
hmm.. this is an interesting problem. Usually spring MVC and jaxrs do their
own instrumentation. Are you saying that these will do instrumentation
while there's also a servlet-level filter in place?

**Comment by pavolloffay** [comment]
At the moment this filter is reused by spring-web. I plan to use it also in jax-rs to trace unauthenticated/no URL mapping requests etc..

**Comment by codefromthecrypt** [comment]
Is it code re-use (like one layer calls library code here) or are you
sharing spans between layers? Ex one instrumentation depends on span
created by this filter? curious

**Comment by pavolloffay** [comment]
in spring-web yes, I run into various issues and this seemed as the best for spring-web. In jax-rs preferred solution would be to create a new span I guess.

**Comment by codefromthecrypt** [comment]
Ok. If makes sense to you, maybe a test dep on one or the other side of
this (or emulate the pattern mentioned in a test). Because that would help
make sure you can do what you want even if someone else is maintaining.
Theres often an assumption of a single span per RPC (at layer where http
method might be the span name) though you are right that if different
people are writing instrumentation and applying it without coordnation you
might end up with double or triply implemented spans.

On 10 Apr 2017 11:02 pm, "Pavol Loffay" <notifications@github.com> wrote:

in spring-web yes, I run into various issues and this seemed as the best
for spring-web. In jax-rs preferred solution would be to create a new span
I guess.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/opentracing-contrib/java-web-servlet-filter/issues/15#issuecomment-292976941>,
or mute the thread
